In [163]:
import numpy as np
import pickle
import random
import csv,sys

# Load Glove

In [12]:
file_name = '/scratch/ql819/Tweets/glove/glove.twitter.27B.100d.txt'
#glove_vocab = []
#glove_embed = []
embedding_dict = {}

file = open(file_name, 'r', encoding = 'UTF-8')

for line in file.readlines():
    row = line.strip().split(' ')
    vocab_word = row[0]
    #glove_vocab.append(vocab_word)
    embed_vector = [float(i) for i in row[1:]]
    embedding_dict[vocab_word] = np.array(embed_vector)
    #glove_embed.append(embed_vector)

In [20]:
embedding_dict['wrestling']

array([ 0.070878 , -0.38237  ,  0.19812  , -0.56706  , -0.10155  ,
        0.26353  ,  0.78261  ,  0.43845  ,  0.18323  ,  0.21758  ,
        0.14789  , -0.49593  , -2.8569   ,  0.46476  ,  1.1635   ,
       -0.10135  , -0.80285  , -0.53834  , -0.11441  ,  0.19423  ,
       -0.20462  ,  1.0603   ,  0.55811  , -0.083468 , -0.58797  ,
        0.48816  ,  0.15013  , -0.65217  , -0.75158  , -0.0047128,
       -0.039005 , -0.16217  ,  0.41973  , -0.11195  ,  0.39354  ,
        0.14858  ,  0.95279  , -0.36303  ,  0.51631  , -0.20326  ,
       -0.0095533, -1.1235   , -0.2453   ,  0.43147  ,  0.62233  ,
        0.43189  , -0.28003  ,  0.16717  ,  0.55168  , -0.6711   ,
        0.10667  , -0.39833  ,  0.092899 ,  0.12986  ,  0.16449  ,
        0.059435 ,  0.25194  ,  0.11007  , -0.4768   , -0.35162  ,
        0.57028  , -0.55725  , -0.45958  , -0.52199  , -0.39543  ,
       -0.058108 ,  0.53706  ,  0.8578   ,  0.91095  , -0.54477  ,
       -0.044107 , -0.36909  , -0.17281  ,  0.16893  , -0.3310

# Load Key Word and calculate embedding representation for each key word

In [47]:
activity_key_words = pickle.load(open('../store_key_word/activity.pickle', 'rb'))
activity_key_words = [item.strip() for item in activity_key_words]

key_words_embedding_activity = {}
not_match = np.array([np.nan] * 100)
for key_item in activity_key_words:
    list_np = [embedding_dict.get(word,not_match) for word in key_item.split(' ')]
    list_np = np.vstack(list_np)
    key_words_embedding_activity[key_item] = np.nanmean(list_np, axis=0)
    
key_words_embedding_activity = dict(filter(lambda x: not np.isnan(x[1])[0], key_words_embedding_activity.items()))

/home/ql819/pytorch-cpu/py3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: Mean of empty slice
  if __name__ == '__main__':


In [54]:
food_key_words = pickle.load(open('../store_key_word/food.pickle', 'rb'))
food_key_words = [item.strip() for item in food_key_words]
#food_key_words.append('hamburger')

key_words_embedding_food = {}
not_match = np.array([np.nan] * 100)
for key_item in food_key_words:
    list_np = [embedding_dict.get(word,not_match) for word in key_item.split(' ')]
    list_np = np.vstack(list_np)
    key_words_embedding_food[key_item] = np.nanmean(list_np, axis=0)
    
key_words_embedding_food = dict(filter(lambda x: not np.isnan(x[1])[0], key_words_embedding_food.items()))

/home/ql819/pytorch-cpu/py3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: Mean of empty slice
  if __name__ == '__main__':


In [86]:
key_words_embedding_activity['run']

array([-3.7545e-02,  1.1898e-01,  2.6445e-01, -7.6977e-01,  8.6135e-02,
        4.9159e-01,  6.5186e-01,  3.3472e-01, -2.8600e-01,  1.8043e-01,
        4.3625e-01,  2.5313e-01, -3.7646e+00,  3.6397e-01, -6.4090e-01,
       -4.9278e-01, -3.2588e-01, -8.0788e-02, -5.5677e-01, -2.4818e-01,
       -2.6804e-02, -1.4919e-01, -6.3853e-02, -3.5695e-01,  2.2165e-01,
        2.7029e-02, -1.9695e-01,  1.5099e-01, -1.1226e-01,  1.5583e-01,
        2.1070e-01,  1.4041e-01, -2.9264e-01,  5.6477e-01,  2.0825e-03,
        3.1600e-01,  1.8472e-01, -4.9405e-01, -3.3496e-01,  2.9211e-01,
       -5.4029e-01,  8.7934e-01, -3.9010e-01,  6.5981e-02,  3.6901e-01,
       -2.8464e-02,  1.5208e-01,  7.1456e-01,  4.8595e-01,  2.2912e-01,
       -2.4792e-01, -2.3986e-01,  5.0812e-01,  5.0515e-01, -3.8752e-01,
       -2.4902e-01,  1.7928e-02,  5.8749e-02, -3.0073e-01, -2.6155e-02,
        5.7714e-03, -1.3286e-01,  4.3251e-04, -1.3966e-01,  3.6019e-01,
       -4.0055e-01, -1.2270e-01, -4.3459e-02,  1.2906e-01, -2.94

In [102]:
key_words_embedding_food['salmon']

array([-0.42112  , -0.21374  ,  0.0040391, -0.19908  ,  0.053068 ,
       -0.11377  ,  0.31579  , -0.58126  , -0.43308  , -0.17787  ,
        0.29681  ,  0.18923  , -1.4589   ,  0.10148  , -0.41679  ,
        0.13242  ,  0.64401  , -0.36636  ,  0.40502  ,  0.10571  ,
        0.16061  , -0.27589  , -1.1044   , -0.52718  ,  0.48075  ,
        0.48371  , -0.1668   , -0.27481  , -0.19933  , -0.30383  ,
        0.092113 ,  0.22367  , -0.21019  , -0.74207  , -0.49321  ,
       -0.91909  ,  0.086601 ,  0.51941  ,  0.40646  ,  0.61456  ,
       -0.0051479, -0.33896  , -0.047362 ,  0.56601  ,  0.86746  ,
        0.28095  , -0.16091  ,  0.63973  ,  1.2355   , -0.76863  ,
       -0.59568  , -0.15055  ,  0.36573  ,  0.37697  ,  0.33415  ,
       -0.62394  ,  1.2061   , -0.59272  ,  0.83349  ,  0.69309  ,
       -0.40331  , -0.23807  , -0.75458  ,  0.18594  ,  0.31011  ,
       -0.0074961, -0.35564  , -0.49051  , -0.47419  , -0.64183  ,
        0.34882  ,  0.1417   ,  0.14137  ,  0.26313  ,  1.1137

# Calculate average word embedding for food and activity

In [101]:
avg_activity_word_embedding = [np_list for np_list in key_words_embedding_activity.values()]
avg_activity_word_embedding = np.vstack(avg_activity_word_embedding)
avg_activity_word_embedding = np.mean(avg_activity_word_embedding, axis=0)
avg_activity_word_embedding

array([-0.08789521, -0.12662818,  0.17837505, -0.25753277,  0.18943437,
        0.27984903,  0.17782452, -0.05814933,  0.09088858, -0.21618454,
        0.0552833 ,  0.05297766, -2.27854995,  0.1460505 ,  0.02979897,
       -0.10999084, -0.10135598, -0.0428869 , -0.02375249,  0.03479561,
       -0.23797928,  0.15196736,  0.17087834, -0.07052562,  0.06050996,
        0.39400038, -0.11312828,  0.28280854, -0.15376193, -0.04082689,
        0.04480472, -0.03182786,  0.20487094, -0.10702942,  0.08409915,
        0.12387256,  0.24865125,  0.04848354,  0.22096025,  0.31769506,
       -0.16933218,  0.08779802, -0.11178278,  0.13234026,  0.33968599,
        0.11277588,  0.09413708,  0.33241916,  0.04865954, -0.07330837,
        0.29735722,  0.01335191, -0.04835534, -0.01072055, -0.1965817 ,
       -0.11439727,  0.2218295 , -0.10684127,  0.00446674,  0.18400208,
        0.0366111 ,  0.09944915, -0.06515118, -0.213053  , -0.01532658,
       -0.16755079,  0.04699103, -0.01201145,  0.30025454, -0.18

In [103]:
avg_food_word_embedding = [np_list for np_list in key_words_embedding_food.values()]
avg_food_word_embedding = np.vstack(avg_food_word_embedding)
avg_food_word_embedding = np.mean(avg_food_word_embedding, axis=0)
avg_food_word_embedding

array([-3.18748498e-01, -2.92965645e-01,  2.52996252e-02,  1.84988628e-01,
       -7.29455328e-02,  7.20710051e-02, -2.39598092e-02, -8.86421021e-02,
        4.10698158e-02, -4.27165344e-01, -1.37892269e-01, -1.81628771e-02,
       -1.62943874e+00, -1.71823236e-01, -1.01707025e-01,  2.07938805e-01,
        3.87922445e-01,  5.94374872e-02,  8.80814799e-02,  4.15215148e-02,
       -4.57780154e-02,  3.41082135e-02, -2.56759330e-01,  1.15337854e-01,
        8.71791403e-02,  3.89588812e-01, -1.16866566e-01, -3.95778080e-02,
        5.18544035e-02,  8.44636156e-03,  9.21848045e-04,  4.16343399e-01,
       -1.20451218e-01, -3.34404485e-01, -2.94733878e-01, -3.19710636e-01,
       -4.90131703e-02,  9.20723694e-02,  2.64664139e-01,  5.62278246e-01,
        3.85023448e-02, -1.16345527e-01, -3.16479447e-01,  3.02896291e-01,
        2.51448119e-01,  1.41341923e-01, -1.12162814e-01,  4.65822328e-01,
        3.81651331e-01, -1.99104461e-01, -5.60276236e-02, -6.74228949e-02,
       -1.29833090e-01,  

# another way to calculate the distance

In [115]:
several_food_list = ['vegetables', 'fruit', 'grain', 'meat', 'milk', 'food']
several_activity_list = ['swimming', 'walking', 'jogging', 'soccer', 'football', 'basketball', 'cycling', 'activity']

In [121]:
several_food_list_embedding = {item:embedding_dict[item] for item in several_food_list}
several_activity_list_embedding = {item:embedding_dict[item] for item in several_activity_list}

# Calculate distance

In [158]:
def calculate_distance(sentence):
    
    list_np = [embedding_dict.get(word,not_match) for word in sentence.split(' ')]
    list_np = [item for item in list_np if not np.isnan(item)[0]]
    if len(list_np) >= 1:
        list_np = np.vstack(list_np)
        
        #1. distance between sentence average embeding and average food and actvity embedding
        sentence_average_embedding = np.mean(list_np, axis=0)
        distance_1_food = np.linalg.norm(sentence_average_embedding - avg_food_word_embedding)
        distance_1_activity = np.linalg.norm(sentence_average_embedding - avg_activity_word_embedding)
        
        #2. distance between sentence average embedding and word 'food' and 'activity' embedding
        distance_2_food = np.linalg.norm(sentence_average_embedding - embedding_dict['food'])
        distance_2_activity = np.linalg.norm(sentence_average_embedding - embedding_dict['activity'])
        
        #3. minimum distance between sentence word and word 'food' and 'activity' embedding
        distance_3_food = min([np.linalg.norm(list_np[row_index] - embedding_dict['food']) \
                                   for row_index in range(list_np.shape[0])])
        distance_3_activity = min([np.linalg.norm(list_np[row_index] - embedding_dict['activity']) \
                                   for row_index in range(list_np.shape[0])])
        
        #4. minimun distance between sentence work and several_food_list and several_activity_list
        distance_4_food = []
        distance_4_activity = []
        for word_embedding in several_food_list_embedding.values():
            distance_4_food.extend([np.linalg.norm(list_np[row_index] - word_embedding) \
                                   for row_index in range(list_np.shape[0])])
        
        for word_embedding in several_activity_list_embedding.values():
            distance_4_activity.extend([np.linalg.norm(list_np[row_index] - word_embedding) \
                                   for row_index in range(list_np.shape[0])])
            
        distance_4_food = min(distance_4_food)
        distance_4_activity = min(distance_4_activity)
        
        return [distance_1_food,distance_1_activity,distance_2_food,distance_2_activity,
               distance_3_food,distance_3_activity,distance_4_food,distance_4_activity]
        
    else:
        return False

In [161]:
if [1]:
    print('ok')

ok


In [166]:
from_csv_list = ['/scratch/ql819/Tweets/token_id_time_state/2014-06_key_work_id_state_time.csv',
                 '/scratch/ql819/Tweets/token_id_time_state/2014-11_key_work_id_state_time.csv',
                 '/scratch/ql819/Tweets/token_id_time_state/2015-06_key_work_id_state_time.csv',
                 '/scratch/ql819/Tweets/token_id_time_state/2015-11_key_work_id_state_time.csv']

to_csv_list = ['/scratch/ql819/Tweets/similar_sentence/2014-06.csv',
                 '/scratch/ql819/Tweets/similar_sentence/2014-11.csv',
                 '/scratch/ql819/Tweets/similar_sentence/2015-06.csv',
                 '/scratch/ql819/Tweets/similar_sentence/2015-11.csv']

#index = int(sys.argv[1])
index = 2

from_csv = from_csv_list[index]
to_csv = to_csv_list[index]
print(from_csv,to_csv)
sys.stdout.flush()


fp = open(to_csv, "a") 
wr = csv.writer(fp, dialect='excel')

with open(from_csv) as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    for row in readCSV: 
        tweet = row[4]
        result = calculate_distance(tweet)
        if result:
            row.extend(result)
            wr.writerow(row)

fp.close()

/scratch/ql819/Tweets/token_id_time_state/2015-06_key_work_id_state_time.csv /scratch/ql819/Tweets/similar_sentence/2015-06.csv


In [ ]:
header = ['ID', 'timestamp', 'Day_of_Week', 'State', 'Tweet', 'mentioned_food',
         'mentioned_activity', 'target', 'distance_1_food','distance_1_activity',
          'distance_2_food','distance_2_activity','distance_3_food','distance_3_activity',
          'distance_4_food','distance_4_activity']